# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_semisupnnmf <- function(A, k, W, H, Wm, Hm, max_iter, rel_tol, n_threads, verbose, show_warning, inner_max_iter, inner_rel_tol, trace) {
    .Call(`_semiSupNMF_c_semisupnnmf`, A, k, W, H, Wm, Hm, max_iter, rel_tol, n_threads, verbose, show_warning, inner_max_iter, inner_rel_tol, trace)
}

